# Generated by Django 5.2.4 on 2025-07-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("photo", "Photo"), ("video", "Video")],
                        max_length=10,
                        verbose_name="type",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="media_center/", verbose_name="file"),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Optional. A thumbnail image for the media.",
                        null=True,
                        upload_to="media_center/",
                        verbose_name="thumbnail",
                    ),
                ),
                (
                    "hls_playlist",
                    models.URLField(
                        blank=True,
                        help_text="Path to the HLS playlist (.m3u8) file.",
                        max_length=2048,
                        null=True,
                        verbose_name="HLS Playlist",
                    ),
                ),
                (
                    "phash",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Perceptual Hash",
                    ),
                ),
            ],
            options={
                "verbose_name": "media",
                "verbose_name_plural": "media",
                "indexes": [
                    models.Index(fields=["phash"], name="media_cente_phash_b53fdc_idx"),
                    models.Index(fields=["type"], name="media_cente_type_c483fa_idx"),
                ],
            },
        ),
    ]
